name: Check for go mod changes
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod

      - name: Test go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
